#!/usr/bin/env python3
"""Static audit of data/dbc/*.dbc: duplicates, orphan references, size, tier.
Writes DBC_AUDIT.md in the repo root (not in data/, which is flashed to the device)
and data/dbc/manifest.json (name, size, SHA-256, tier, use). Tiers are a heuristic
by file name only; they say nothing about licence or about which market a file
really targets. Source and licence are always written as "unverified".

  python3 scripts/audit_dbc.py          regenerate both files
  python3 scripts/audit_dbc.py --check  fail if manifest.json is out of date
"""
import hashlib, json, os, re, sys

# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
# □□□□□□□□□□ Configuration
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

D = os.path.join(os.path.dirname(__file__), "..", "data", "dbc")
SPECIALIZED = re.compile(r"(object|radar|adas|actuator|park_assist|party|lowspeed|chassis|"
                         r"high_voltage|body|ESR|CADS|_exp|dsu|tssp)", re.I)
ESSENTIAL = re.compile(r"(psa_|hyundai|toyota_(2017|prius|iQ)|nissan|mazda_(2017|3)|"
                       r"mg\.|hongqi|gwm|luxgen|vw_(mqb|pq)\b|vw_mqb\.)", re.I)

# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
# □□□□□□□□□□ Checks
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

def tier(n):
    if SPECIALIZED.search(n): return "specialized"
    if ESSENTIAL.search(n): return "essential"
    return "supplemental"

ROOT = os.path.join(os.path.dirname(__file__), "..")
vehicle_src = open(os.path.join(ROOT, "src", "vehicle_db.cpp"), encoding="utf-8").read()
fs_src = open(os.path.join(ROOT, "scripts", "cartouch_4mb_fs.py"), encoding="utf-8").read()
profile_count = {}
for ref in re.findall(r'_addVeh\([^;]*?"/dbc/([^"]+\.dbc)"', vehicle_src):
    profile_count[ref] = profile_count.get(ref, 0) + 1
in_4mb = set(re.findall(r'"dbc/([^"]+\.dbc)"', fs_src))

rows, hashes, problems, manifest = [], {}, 0, []
for f in sorted(os.listdir(D)):
    if not f.lower().endswith(".dbc"): continue
    raw = open(os.path.join(D, f), "rb").read()
    t = raw.decode("latin-1")
    ids = re.findall(r"^BO_ (\d+) ", t, re.M)
    known = set(ids)
    orphan = len({m for m in re.findall(r"^(?:VAL_|CM_ SG_) (\d+) ", t, re.M) if m not in known})
    dupid = len(ids) - len(known)
    h = hashlib.md5(raw).hexdigest()
    same = hashes.setdefault(h, f)
    if same != f: problems += 1
    if dupid: problems += 1
    rows.append((f, len(raw), len(ids), orphan, dupid, tier(f), same if same != f else ""))
    manifest.append({"name": f, "size": len(raw), "sha256": hashlib.sha256(raw).hexdigest(),
                     "messages": len(ids), "tier": tier(f), "profiles": profile_count.get(f, 0),
                     "in4mb": f in in_4mb, "source": "unverified", "license": "unverified"})

manifest_text = ('{"format":1,"files":[\n' +
                 ",\n".join(json.dumps(m, separators=(",", ":")) for m in manifest) + "\n]}\n")
manifest_path = os.path.join(D, "manifest.json")
if "--check" in sys.argv:
    current = open(manifest_path, encoding="utf-8").read() if os.path.isfile(manifest_path) else ""
    if current != manifest_text:
        print("data/dbc/manifest.json is out of date; run: python3 scripts/audit_dbc.py")
        sys.exit(1)
    print(f"manifest.json matches {len(manifest)} DBC files")
    sys.exit(1 if problems else 0)
open(manifest_path, "w", encoding="utf-8", newline="\n").write(manifest_text)

out = ["# DBC audit (generated by scripts/audit_dbc.py)", "",
       "Tier is a name-based heuristic. Source and licence of each file are NOT",
       "verified; see THIRD_PARTY_NOTICES.md. Orphan = comment/value-table rows that",
       "point to a message id missing from the same file (harmless, not parsed).", "",
       "| File | Bytes | Messages | Orphan refs | Dup ids | Tier | Duplicate of | Profiles | In 4 MB image |",
       "|---|---|---|---|---|---|---|---|---|"]
out += ["| " + " | ".join(map(str, r)) + f" | {profile_count.get(r[0], 0)} | {'yes' if r[0] in in_4mb else 'no'} |" for r in rows]
unused = [r[0] for r in rows if profile_count.get(r[0], 0) == 0]
out += ["", f"Files with no vehicle profile (not selectable in the UI): {len(unused)}", ""]
out += ["- " + n for n in unused]
open(os.path.join(os.path.dirname(__file__), "..", "DBC_AUDIT.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{len(rows)} files, {problems} hard problems")
sys.exit(1 if problems else 0)
